name: portfolio
description: "Shikhar Bajpai - Flutter Portfolio App"
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ^3.11.3


dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  flutter_staggered_animations: ^1.1.1


 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pfp.jpeg
    - assets/todo1.jpeg
    - assets/todo2.jpeg
    - assets/todo3.jpeg
    - assets/dice.png
    - assets/iot1.png
    - assets/iot2.png
    - assets/codein1.png
    - assets/codein2.png
    - assets/codein3.png
    - assets/codein4.png
    - assets/codein5.png
    - assets/codein6.png
    - assets/codein7.png
    - assets/codein8.png
    - assets/metro1.jpg
    - assets/metro2.jpg
    - assets/metro3.jpg
    - assets/metro4.jpg
    - assets/metro5.jpg
    - assets/metro6.jpg
    - assets/metro7.jpg
    - assets/metro8.jpg
    - assets/metro9.jpg
    - assets/metro10.jpg
  


  